name: CI/CD Pipeline (Minikube - Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker (Windows)
      - name: Set up Docker (Windows)
        shell: powershell
        run: docker version

      # 3️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t silvesteranto/webapp:latest .

      # 5️⃣ Test the Docker image (basic container run)
      - name: Test the Docker image
        shell: powershell
        run: |
          docker run -d -p 8080:80 --name test-webapp silvesteranto/webapp:latest
          Start-Sleep -Seconds 5
          docker ps | Select-String test-webapp
          docker stop test-webapp
          docker rm test-webapp

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        shell: powershell
        run: |
          docker push silvesteranto/webapp:latest

      # 7️⃣ Verify Docker images list
      - name: List Docker images
        shell: powershell
        run: docker images
