name: CI/CD Pipeline (Minikube - Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Point Docker to Minikube
      - name: Set Docker environment to Minikube
        shell: powershell
        run: |
          minikube -p minikube docker-env | Invoke-Expression

      # 3️⃣ Build Docker image inside Minikube
      - name: Build Docker image
        shell: powershell
        run: docker build -t webapp:latest .

      # 4️⃣ Verify image
      - name: List Docker images
        shell: powershell
        run: docker images
