name: GOVT-PREP CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest   # ✅ switch to Linux runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t silvesteranto/webapp:latest .

      # 5️⃣ Test the Docker image
      - name: Test Docker image
        run: |
          docker run -d -p 8080:80 --name test-webapp silvesteranto/webapp:latest
          sleep 5
          docker ps | grep test-webapp
          docker stop test-webapp
          docker rm test-webapp

      # 6️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push silvesteranto/webapp:latest
